# Generated by Django 4.0.4 on 2022-06-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('phone', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Пациента', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='secondname',
        ),
        migrations.AlterField(
            model_name='client',
            name='birth',
            field=models.IntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=20, unique=True, verbose_name='Серия и номер пасспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
