# Generated by Django 4.0.4 on 2022-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_temp_alter_client_options_remove_client_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.IntegerField(default=1, verbose_name='Год рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Серия и номер пасспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('ID CARD', 'Id Card'), ('BIOMETRIC PASSPORT', 'Biometric Passport'), ('DRIVER LICENSE', 'Driver License')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('PATIENT', 'Patient')], max_length=15),
        ),
    ]
