# Generated by Django 4.0.4 on 2022-06-03 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('buyed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=256, verbose_name='Член Семьи')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_doc', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_pat', to=settings.AUTH_USER_MODEL)),
                ('recept', models.ManyToManyField(to='medbook.recepts', verbose_name='Рецепт')),
            ],
        ),
    ]
