# Generated by Django 4.0.4 on 2022-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbook', '0003_medbook_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='medbook',
            name='f_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
